docs: add more on implicit differentiation
metaopt/torchopt pull request #143
Opened 2023-03-01 14:39 UTC by Benjamin-eecs

## Description

add more docs on implicit differentiation

## Types of changes

- [x] Documentation (update in the documentation)

## Checklist

- [x] I have read the [CONTRIBUTION](https://torchopt.readthedocs.io/en/latest/developer/contributing.html) guide. (**required**)
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format`. (**required**)
- [x] I have checked the code using `make lint`. (**required**)
- [x] I have ensured `make test` pass. (**required**)

2023-03-06 09:31 UTC, XuehaiPan approved these changes

2023-03-09 00:17 UTC, waterhorse1 commented on docs/source/implicit_diff/implicit_diff.rst
> +
Can we do something like this. We use the equation T (\boldsymbol{\phi}, \boldsymbol{\theta}^{\prime}(\boldsymbol{\phi})) = \boldsymbol{0} and say if the solution of the inner-loop optimization is a root for such function, one can use implicit gradient.

Then we list two subsections, (need to split them up so it is clear) say for example, when we use gradient descent to solve for the optimization, the above equation is instantiated by the (first-order gradient =0). This is the subsection of IMAML.

Then the subsection of fixed-point, say DEQ, in this case the equation is instantiated by T-\theta = 0.

And also need to address that F is the iterative function, T is the stationary function at the beginning of these two subsections.

2023-03-09 05:47 UTC, XuehaiPan requested changes
Misunderstanding for $T$ and $F$.

2023-03-09 08:43 UTC, XuehaiPan approved these changes

2023-03-09 09:21 UTC, merged