Implicit differentiation integration
metaopt/torchopt pull request #41
Opened 2022-07-25 06:33 UTC by Benjamin-eecs

#13

2022-08-10 14:32 UTC, XuehaiPan requested changes
Please fetch the latest upstream, and rebase your commits. Besides, don't forget to setup the pre-commit hooks.

2022-09-06 12:11 UTC, XuehaiPan submitted a review, later dismissed

2022-09-06 13:59 UTC, XuehaiPan approved these changes

2022-09-07 06:33 UTC, XuehaiPan commented on torchopt/_src/linalg.py
> +    atol2 = max(rtol**2 * bs, atol**2)
`bs` could be a tree of tensors (e.g. `dict` of tensors). Comparing to float can be failed.

2022-09-07 06:34 UTC, XuehaiPan commented on torchopt/_src/linalg.py
> +        return (rs > atol2) & (k < maxiter)
This may also be a tensor.

2022-09-07 09:43 UTC, XuehaiPan submitted a review, later dismissed

2022-09-07 16:16 UTC, waterhorse1 approved these changes

2022-09-08 07:08 UTC, XuehaiPan submitted a review, later dismissed

2022-09-08 07:21 UTC, XuehaiPan approved these changes

2022-09-08 11:53 UTC, merged