Implement Rmsprop optimiser
metaopt/TorchOpt pull request #8
Opened 2022-04-29 08:38 UTC by future-xy

2022-04-29 09:00 UTC, JieRen98 requested changes

2022-04-29 09:34 UTC, future-xy commented on TorchOpt/_src/transform.py
> +      def f(g, n): return g.mul_(torch.rsqrt_(n.add_(eps)))
修改了这里，同理还修正了其他会修改n的地方。另外修了一个test脚本的bug。

2022-04-29 09:38 UTC, JieRen98 requested changes

2022-04-29 09:38 UTC, JieRen98 commented on TorchOpt/_src/transform.py
> +    #   def f(g, n): return g.div_(torch.sqrt_(n).add_(eps))
建议把这个也修改一下，似乎应该是torch.sqrt(n).add_

2022-04-29 09:48 UTC, JieRen98 commented
是不是应该RMSprop -> RMSProp涅？

2022-04-29 09:51 UTC, future-xy commented
TF/PyTorch/Keras是RMSprop，Optax是RMSProp。那就按照Optax来吧

2022-04-29 09:57 UTC, JieRen98 commented
> TF/PyTorch/Keras是RMSprop，Optax是RMSProp。那就按照Optax来吧

我看挺多论文都叫RMSProp

2022-04-29 09:59 UTC, future-xy commented on TorchOpt/_src/transform.py
> +    #   def f(g, n): return g.div_(torch.sqrt_(n).add_(eps))
358行吗？

2022-04-30 13:58 UTC, future-xy commented
> > TF/PyTorch/Keras是RMSprop，Optax是RMSProp。那就按照Optax来吧
> 
> 我看挺多论文都叫RMSProp

已提交修改

2022-05-01 11:18 UTC, JieRen98 commented on TorchOpt/_src/transform.py
> +    #   def f(g, n): return g.div_(torch.sqrt_(n).add_(eps))
是的

2022-05-01 11:21 UTC, JieRen98 approved these changes

2022-05-01 11:22 UTC, merged